CREATE TABLE pageviews (
  id SERIAL PRIMARY KEY,
  view_time TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  url varchar(2083) NOT NULL,
  user_agent VARCHAR(2083) NOT NULL,
  referrer VARCHAR(2083) NOT NULL,
  device_type SMALLINT NOT NULL DEFAULT 0
);
